# Generated by Django 5.2.5 on 2025-09-01 19:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='contractor_type',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('transaction_type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход'), ('transfer', 'Перевод'), ('debt_give', 'Дать в долг'), ('debt_receive', 'Получить в долг'), ('debt_repay', 'Вернуть долг'), ('debt_received', 'Получить возврат долга')], max_length=20, verbose_name='Тип операции')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control.category', verbose_name='Категория')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='control.contractor', verbose_name='Контрагент')),
                ('estimate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='control.estimate', verbose_name='Смета')),
                ('estimate_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='control.estimateitem', verbose_name='Пункт сметы')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
