# Generated by Django 5.2.5 on 2025-09-01 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_category_remove_contractor_contractor_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='total_amount',
        ),
    ]
