# Generated by Django 5.2.5 on 2025-09-01 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_remove_estimate_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='control.stage', verbose_name='Этап'),
        ),
    ]
