# Generated by Django 5.2.5 on 2025-09-02 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_transaction_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
        migrations.AddField(
            model_name='project',
            name='contractor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='control.contractor', verbose_name='Заказчик'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
