# Generated by Django 5.2.5 on 2025-09-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_remove_project_client_project_contractor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание'),
        ),
    ]
