# Generated by Django 5.2.5 on 2025-09-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_alter_transaction_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='from_project',
        ),
        migrations.RemoveField(
            model_name='debt',
            name='to_project',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='estimate',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='estimate_item',
        ),
        migrations.DeleteModel(
            name='ExpenseType',
        ),
        migrations.RemoveField(
            model_name='income',
            name='estimate',
        ),
        migrations.RemoveField(
            model_name='income',
            name='estimate_item',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='object',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='project',
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='is_percentage',
            field=models.BooleanField(default=False, verbose_name='Процент'),
        ),
        migrations.DeleteModel(
            name='Debt',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
