# Generated by Django 5.2.5 on 2025-09-02 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_remove_debt_from_project_remove_debt_to_project_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estimateitem',
            options={'ordering': ['estimate', 'id'], 'verbose_name': 'Элемент сметы', 'verbose_name_plural': 'Элементы сметы'},
        ),
        migrations.RemoveField(
            model_name='estimateitem',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='estimateitem',
            name='material',
        ),
        migrations.RemoveField(
            model_name='estimateitem',
            name='work_type',
        ),
        migrations.CreateModel(
            name='PriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('unit', models.CharField(max_length=50, verbose_name='Единица измерения')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за единицу')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_items', to='control.materialtype', verbose_name='Материал')),
                ('work_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_items', to='control.worktype', verbose_name='Вид работ')),
            ],
            options={
                'verbose_name': 'Позиция прайса',
                'verbose_name_plural': 'Позиции прайса',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='price_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_items', to='control.priceitem', verbose_name='Позиция прайса'),
        ),
    ]
