# Generated by Django 5.2.5 on 2025-09-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_alter_estimateitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimateitem',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='priceitem',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Цена за единицу'),
        ),
    ]
