# Generated by Django 5.2.5 on 2025-09-02 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0009_alter_estimateitem_description_and_more'),
    ]

    operations = [
    ]
