# Generated by Django 5.2.5 on 2025-09-02 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0010_auto_20250902_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialtype',
            name='unit',
        ),
    ]
