# Generated by Django 5.2.5 on 2025-11-07 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0011_remove_materialtype_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Контрагент'),
        ),
        migrations.DeleteModel(
            name='Contractor',
        ),
    ]
