# Generated by Django 5.2.5 on 2025-12-03 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0013_customuser_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_objects', to='control.project', verbose_name='Проект'),
        ),
    ]
